### ISSUE TITLE
PC Board file is needed

### ISSUE THREAD

**Issue by reifsnyderb** [reifsnyderb/Apple-II-R0#1]
PC Board file is missing as it was made from imported gerber files from M. Willegal's Apple II Revision 0 board.  KiCad, unfortunately, imported them with the wrong track thickness.  Extensive work will be required to re-set the track thicknesses properly.

**Comment by jimbro1000** [comment]
I've started routing tracks by hand based on those gerbers and found some issues with the schematics as a result - will post them as separate issues

**Comment by reifsnyderb** [comment]
PCB board is now available.  Closing issue.
