### ISSUE TITLE
Loose ends

### ISSUE THREAD

**Issue by jimbro1000** [reifsnyderb/Apple-II-R0#23]
There are two incomplete tracks in the original gerbers
Net-(E2A-O0) heads west near the edge of the board (just above E1) but I can't identify anything it intended to connect to

The Color_Burst trace heads west from R6 (connects R6,R7 and R8). It looks as though there was meant to be a fourth resistor in the bank but was not implemented. There is nowhere for the pads to fit as the traces from J14 occupy that space

Before I simply delete the loose ends can you verify I haven't missed anything against the old boards you have?
This is an otherwise cosmetic problem

**Comment by reifsnyderb** [comment]
The Color_Burst trace goes to a via that appears it could be used as a test point. The metal around the via is masked off.  If the via size is unclear, let me know and I'll take some accurate measurements.  I also checked Mike Willegal's site and he has a close-up of this area and this trace (and via) is on the original Apple II R 0.

The E2A-O0 appears on the board as well.  It terminates as a VIA.  I found a close-up here:  https://medium.com/@piedad/prime-properties-for-sale-e398359440a  So, it appears it should be left in place.
