### ISSUE TITLE
H14 - Pin 6 incorrect

### ISSUE THREAD

**Issue by jimbro1000** [reifsnyderb/Apple-II-R0#8]
This is tied to ground on the PCB

**Comment by reifsnyderb** [comment]
This issue is rather somewhat conflicting.  The PCB clearly ties this to ground.  However, H14 pin 6 of the 74LS251 is an output and would be shorted out to ground when it is high.  Maybe this is a PCB error?

**Comment by reifsnyderb** [comment]
A note has been put on the schematic as a temporary measure.

**Comment by reifsnyderb** [comment]
Attempting to contact Mike Willegal to determine if this was an error on the Apple II Rev 0 boards.

**Comment by reifsnyderb** [comment]
This has been confirmed, by Mike Willegal, to be a mistake and will be corrected on the PCB.

**Comment by reifsnyderb** [comment]
PCB has been fixed.
